### ISSUE TITLE
OpenMM not found

### ISSUE THREAD

**Issue by Steboss** [michellab/Sire#64]
Hi all,

I was trying to install the new version of Sire on my workstation (Ubuntu 14.04, gcc 4.6)
Unfortunately both trying "build_corelib + cmake" and "./compile_sire" the system was unable to find  the openmm folder (OPENMM_ROOT_DIR - exported in the bashrc)
I have tried to install OpenMM-6.3 but nothing changes
The only way to install and let Sire to find OpenMM has been to modify the CMakeList.txt in corelib at line 750 as:
" 
set(OpenMM_ROOT_DIR "/home/steboss/local/openmm")
FIND_PACKAGE( OpenMM )
"
deleting the "option" command 

Should I do this in another (less dangerous) way? is it an issue?

**Comment by Steboss** [comment]
Update:

Thanks to Antonia OpenMM has been recognized, passing through ccmake.
Anyway a problem occur in wrapper installation

I am trying now to install with  conda
It seems that using the latest version of Miniconda (3-latest, 3.9.1, 3.7.3) it's impossible to install openmm with 
conda install openmm
since all the tarball file are impossible to be read
I am trying  to install with conda 3.7.0 and  conda install openmm has been fine

**Comment by chryswoods** [comment]
Closed as this has now been fixed with miniconda

**Comment by jmichel80** [comment]
I'm re opening this issue as installing OpenMM via ./compile-sire.sh still doesn't seem to work for the CPU, CUDA and OpenCL platforms.

This is the output of somd-freenrg after a fresh install on a Ubuntu 14.04.3 box

[ julien@mechagodzilla: ~/projects/D3R/Production/Set2/sire/100~100a/run002/free/output/lambda-0.00 ]$ ~/sire.app/bin/somd-freenrg -C ../../input/sim.cfg -l 0.00 -p CUDA
"/home/julien/sire.app/share/Sire/scripts/somd-freenrg.py" 
Starting /home/julien/sire.app/bin/somd-freenrg: number of threads equals 16

Loading configuration information from file ../../input/sim.cfg

 
Running a somd-freenrg calculation using files ../../input/SYSTEM.top, ../../input/SYSTEM.crd and ../../input/MORPH.pert.
Using parameters:
===============
andersen == True
barostat == True
buffered coordinates frequency == 500
center solute == True
constraint == allbonds
crdfile == ../../input/SYSTEM.crd
cutoff distance == 10 angstrom
cutoff type == cutoffperiodic
energy frequency == 100
equilibrate == True
equilibration iterations == 500
hydrogen mass repartitioning factor == 4.0
lambda array == (0.0, 0.0625, 0.125, 0.1875, 0.25, 0.3125, 0.375, 0.4375, 0.5, 0.5625, 0.625, 0.6875, 0.75, 0.8125, 0.875, 0.9375, 1)
lambda_val == 0.0
minimal coordinate saving == False
minimise == True
morphfile == ../../input/MORPH.pert
ncycles == 100
nmoves == 20000
platform == CUDA
precision == mixed
save coordinates == True
timestep == 0.004 ps
topfile == ../../input/SYSTEM.top
===============

### Running Single Topology Molecular Dynamics Free Energy on unknown ###
###================Setting up calculation=====================###
New run. Loading input and creating restart
lambda is 0.0
Reading topology file "../../input/SYSTEM.top" 
Reading coordinate file "../../input/SYSTEM.crd" 
Building 1255 molecule(s)... 
...building molecule 1000 ... 
 Getting space information  
Read space "PeriodicBox( ( 40.176, 35.4107, 37.4513 ) )" 
...complete 
Create the System...
Selecting dummy groups
Applying Hydrogen Mass repartition to input using a factor of 4.0 
Creating force fields... 
Setting up the simulation with random seed 569680
Setting up moves...
Created a MD move that uses OpenMM for all molecules on 0 
Generated random seed number 569680 
Saving restart
Setting up sim file. 
There are 3788 atoms in the group 
###===========================================================###

###=======================Minimisation========================###
Running minimisation.
Traceback (most recent call last):
  File "/home/julien/sire.app/share/Sire/scripts/somd-freenrg.py", line 142, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/home/julien/sire.app/lib/python3.4/site-packages/Sire/Tools/__init__.py", line 140, in inner
    retval = func()
  File "/home/julien/sire.app/lib/python3.4/site-packages/Sire/Tools/OpenMMMD.py", line 1496, in runFreeNrg
    system = integrator.minimiseEnergy(system, minimise_tol.val, minimise_max_iter.val)
RuntimeError: There is no registered Platform called "CUDA"

OpenCL also fails with...
~/sire.app/bin/somd-freenrg -C ../../input/sim.cfg -l 0.00 -p OpenCL
(...)
###=======================Minimisation========================###
Running minimisation.
Traceback (most recent call last):
  File "/home/julien/sire.app/share/Sire/scripts/somd-freenrg.py", line 142, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/home/julien/sire.app/lib/python3.4/site-packages/Sire/Tools/__init__.py", line 140, in inner
    retval = func()
  File "/home/julien/sire.app/lib/python3.4/site-packages/Sire/Tools/OpenMMMD.py", line 1496, in runFreeNrg
    system = integrator.minimiseEnergy(system, minimise_tol.val, minimise_max_iter.val)
RuntimeError: There is no registered Platform called "OpenCL"


So does CPU

~/sire.app/bin/somd-freenrg -C ../../input/sim.cfg -l 0.00 -p CPU
(...)
###===========================================================###

###=======================Minimisation========================###
Running minimisation.
Traceback (most recent call last):
  File "/home/julien/sire.app/share/Sire/scripts/somd-freenrg.py", line 142, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/home/julien/sire.app/lib/python3.4/site-packages/Sire/Tools/__init__.py", line 140, in inner
    retval = func()
  File "/home/julien/sire.app/lib/python3.4/site-packages/Sire/Tools/OpenMMMD.py", line 1496, in runFreeNrg
    system = integrator.minimiseEnergy(system, minimise_tol.val, minimise_max_iter.val)
RuntimeError: There is no registered Platform called "CPU"

Reference does work 

 ~/sire.app/bin/somd-freenrg -C ../../input/sim.cfg -l 0.00 -p Reference
(...)
Setting up sim file. 
There are 3788 atoms in the group 
###===========================================================###

###=======================Minimisation========================###
Running minimisation.
^CYou're killing me!!!

I, and all of my children are now dead. Adieu...

**Comment by jmichel80** [comment]
Strangely, everything seems to be setup correctly in the build folder to find the OpenMM libraries, this is the relevant output from ccmake . run in sire/build/corelib


 OpenMM_INCLUDE_DIR               /home/julien/sire.app/include                                                                                                                                         
 OpenMM_LIBRARIES                 /home/julien/sire.app/lib/libOpenMM.so                                                                                                                                
 OpenMM_LIBRARIES_D               OpenMM_LIBRARIES_D-NOTFOUND                                                                                                                                           
 OpenMM_PLUGIN_DIR                /home/julien/sire.app/lib/plugins                                                                                                                                     
 OpenMM_ROOT_DIR                  /home/julien/sire.app

**Comment by jmichel80** [comment]
Some useful additional info. It seems that sire detects 3 platforms for the installed version of openmm (strangely not CUDA) 

[ julien@mechagodzilla: ~/sire.app/lib/python3.4/site-packages/simtk ]$ pwd
/home/julien/sire.app/lib/python3.4/site-packages/simtk
[ julien@mechagodzilla: ~/sire.app/lib/python3.4/site-packages/simtk ]$ ~/sire.app/bin/python testInstallation.py 
There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 1.97918e-05
Reference vs. OpenCL: 2.15343e-05
CPU vs. OpenCL: 1.55575e-05

**Comment by ppxasjsm** [comment]
Does this also get fixed when setting the OPENMM_PLUGIN_DIR?

**Comment by jmichel80** [comment]
Yes. We can close this issue. 
However given the time it took me to 'remember' OPENMM_PLUGIN_DIR  we should test that if a user requests to use a CPU, OpenCL or CUDA platform with somd, then we check that this environment variable has been set before attempting to run a calculation.

**Comment by ppxasjsm** [comment]
I'll make sure to make a note of this in the docs.
